# Device Credentials Configuration
# Copy this file to credentials.yaml and customize for your environment
# WARNING: This file contains sensitive information - never commit to git!

ssh_access:
  # SSH key file path (recommended approach)
  key_file: "~/.ssh/chip-map-key"
  
  # Default SSH settings
  default_username: "pi"
  timeout: 10
  
  # Per-device SSH configuration
  devices:
    # Example device configuration (replace with your actual devices)
    - host: "192.168.1.100"
      hostname: "example-device-01"
      username: "pi"
      # Optional: device-specific key file
      # key_file: "~/.ssh/device-specific-key"
      
    - host: "192.168.1.101"
      hostname: "example-device-02"
      username: "ubuntu"
      
    - host: "10.0.0.50"
      hostname: "example-server"
      username: "root"  # Some devices may use root

# Alternative: SSH agent integration (if you prefer using existing SSH config)
use_ssh_agent: true

# Hardware detection settings
hardware_detection:
  # Whether to use sudo for privileged hardware commands
  use_sudo: true
  
  # Commands to run for chip discovery
  commands:
    cpu: ["lscpu", "cat /proc/cpuinfo"]
    memory: ["dmidecode -t memory", "free -h"]
    storage: ["lsblk", "fdisk -l"]
    network: ["lspci | grep -i network", "ip link show"]
    usb: ["lsusb", "lsusb -t"]
